//! Opt-in Z.AI Coding Plan Vision MCP integration.
//!
//! The provider package runs as a short-lived, bounded stdio MCP subprocess.
//! Its exact package version is pinned, the child receives only a minimal
//! environment plus the dynamically resolved Z.AI credential, and local media
//! paths are canonicalized beneath the workspace or session directory before
//! they cross the process boundary.

use std::{
    path::{Path, PathBuf},
    process::Stdio,
    sync::Arc,
};

use tokio::io::{AsyncBufReadExt as _, AsyncReadExt as _, AsyncWriteExt as _, BufReader};

use crate::{
    types::{
        SharedApiKeyProvider, ToolInput, ZAI_CODING_PLAN_PROVIDER_ID,
        output::ToolOutput,
        requirements::{Expr, ToolRequirement},
        resources::{Cwd, SessionFolder},
        tool::{ToolKind, ToolNamespace},
        tool_metadata::{ToolMetadata, shared_resources},
    },
    util::{ProcessGroup, new_process_group},
};

pub const ZAI_VISION_MCP_ENABLE_ENV: &str = "GROK_ZAI_VISION_MCP";
pub const ZAI_VISION_MCP_PACKAGE_VERSION: &str = "0.1.4";
pub const ZAI_VISION_MCP_PACKAGE: &str = "@z_ai/mcp-server@0.1.4";
pub const ZAI_VISION_MCP_PACKAGE_INTEGRITY: &str = "sha512-jPLBKJaTIy7HGYI0VuAaFJIjU3dq5z09CYZNr3QYoHYhCQ2dr5D6qp93oEVxNyvex643dICB7WloHbph2EzlVg==";

pub const ZAI_VISION_DOCTOR_TOOL_NAME: &str = "zai_vision_doctor";
pub const ZAI_VISION_UI_TO_ARTIFACT_TOOL_NAME: &str = "zai_vision_ui_to_artifact";
pub const ZAI_VISION_EXTRACT_TEXT_TOOL_NAME: &str = "zai_vision_extract_text";
pub const ZAI_VISION_DIAGNOSE_ERROR_TOOL_NAME: &str = "zai_vision_diagnose_error";
pub const ZAI_VISION_UNDERSTAND_DIAGRAM_TOOL_NAME: &str = "zai_vision_understand_diagram";
pub const ZAI_VISION_ANALYZE_DATA_TOOL_NAME: &str = "zai_vision_analyze_data";
pub const ZAI_VISION_UI_DIFF_TOOL_NAME: &str = "zai_vision_ui_diff";
pub const ZAI_VISION_ANALYZE_IMAGE_TOOL_NAME: &str = "zai_vision_analyze_image";
pub const ZAI_VISION_ANALYZE_VIDEO_TOOL_NAME: &str = "zai_vision_analyze_video";

const MAX_STDIO_BYTES: usize = 4 * 1024 * 1024;
const MAX_IMAGE_BYTES: u64 = 20 * 1024 * 1024;
const MAX_VIDEO_BYTES: u64 = 8 * 1024 * 1024;
const MAX_PROMPT_CHARS: usize = 16_384;
const MCP_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(300);
const DOCTOR_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);
const MCP_PROTOCOL_VERSION: &str = "2024-11-05";

pub fn zai_vision_mcp_enabled() -> bool {
    parse_vision_mcp_enabled(std::env::var(ZAI_VISION_MCP_ENABLE_ENV).ok().as_deref())
}

fn parse_vision_mcp_enabled(value: Option<&str>) -> bool {
    value.is_some_and(|value| {
        matches!(
            value.trim().to_ascii_lowercase().as_str(),
            "1" | "true" | "yes" | "on"
        )
    })
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ZaiVisionDoctorReport {
    pub node_version: String,
    pub npx_version: String,
    pub package_version: &'static str,
    pub package_integrity: &'static str,
}

impl ZaiVisionDoctorReport {
    fn render(&self) -> String {
        format!(
            "Z.AI Vision MCP diagnostics\nNode: {} (required: >=22)\nnpx: {}\nPackage: @z_ai/mcp-server@{} (exact pin)\nIntegrity: {}\nCredential: provider-bound and injected only into the child environment",
            self.node_version, self.npx_version, self.package_version, self.package_integrity,
        )
    }
}

#[derive(Clone)]
pub struct ZaiVisionClient {
    auth_provider: SharedApiKeyProvider,
    doctor: Arc<tokio::sync::OnceCell<ZaiVisionDoctorReport>>,
}

impl std::fmt::Debug for ZaiVisionClient {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("ZaiVisionClient")
            .finish_non_exhaustive()
    }
}

impl ZaiVisionClient {
    pub fn new(auth_provider: SharedApiKeyProvider) -> Result<Self, xai_tool_runtime::ToolError> {
        if auth_provider.request_auth_provider_id() != Some(ZAI_CODING_PLAN_PROVIDER_ID) {
            return Err(vision_error(
                "zai_vision_authentication",
                "Z.AI Coding Plan authentication is required for Vision MCP",
            ));
        }
        Ok(Self {
            auth_provider,
            doctor: Arc::new(tokio::sync::OnceCell::new()),
        })
    }

    pub async fn doctor(&self) -> Result<ZaiVisionDoctorReport, xai_tool_runtime::ToolError> {
        self.doctor.get_or_try_init(run_doctor).await.cloned()
    }

    /// Analyze a shell-persisted user attachment. This path is generated by
    /// the session and already resides in its private assets directory.
    pub async fn analyze_attachment(
        &self,
        image_path: &Path,
        prompt: &str,
    ) -> Result<String, xai_tool_runtime::ToolError> {
        validate_prompt(prompt)?;
        let source = validate_generated_attachment(image_path, MediaKind::Image)?;
        let result = self
            .call_mcp_tool(
                "analyze_image",
                serde_json::json!({"image_source": source, "prompt": prompt}),
            )
            .await?;
        mcp_text_content(&result)
    }

    async fn call_mcp_tool(
        &self,
        expected_tool: &str,
        arguments: serde_json::Value,
    ) -> Result<serde_json::Value, xai_tool_runtime::ToolError> {
        let _ = self.doctor().await?;
        let auth = crate::types::resolve_zai_coding_plan_request_auth(&self.auth_provider)
            .await
            .map_err(|_| {
                vision_error(
                    "zai_vision_authentication",
                    "Z.AI Coding Plan authentication is required for Vision MCP",
                )
            })?;
        let bearer = auth.bearer_token().map_err(|_| {
            vision_error(
                "zai_vision_authentication",
                "Z.AI Coding Plan authentication is required for Vision MCP",
            )
        })?;

        let isolated_home = tempfile::tempdir().map_err(|_| {
            vision_error(
                "zai_vision_unavailable",
                "Z.AI Vision MCP could not create an isolated runtime directory",
            )
        })?;
        let mut command = tokio::process::Command::new("npx");
        command
            .args(["--yes", ZAI_VISION_MCP_PACKAGE])
            .env_clear()
            .env("HOME", isolated_home.path())
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::null())
            .kill_on_drop(true);
        copy_safe_child_environment(&mut command);
        command.env("Z_AI_API_KEY", bearer).env("Z_AI_MODE", "ZAI");
        new_process_group(&mut command);

        let mut child = command.spawn().map_err(|_| {
            vision_error(
                "zai_vision_unavailable",
                "Z.AI Vision MCP could not start; run zai_vision_doctor",
            )
        })?;
        let mut process_group = ProcessGroup::new().map_err(|_| {
            vision_error(
                "zai_vision_unavailable",
                "Z.AI Vision MCP process isolation is unavailable",
            )
        })?;
        process_group.attach(&child).map_err(|_| {
            vision_error(
                "zai_vision_unavailable",
                "Z.AI Vision MCP process isolation is unavailable",
            )
        })?;
        let stdin = child.stdin.take().ok_or_else(|| {
            vision_error(
                "zai_vision_protocol",
                "Z.AI Vision MCP stdio transport is unavailable",
            )
        })?;
        let stdout = child.stdout.take().ok_or_else(|| {
            vision_error(
                "zai_vision_protocol",
                "Z.AI Vision MCP stdio transport is unavailable",
            )
        })?;
        let mut child = VisionChild {
            child,
            process_group,
            _isolated_home: isolated_home,
        };
        let mut stdin = stdin;
        let mut stdout = BufReader::new(stdout.take((MAX_STDIO_BYTES + 1) as u64));

        let exchange = exchange_vision_mcp(&mut stdout, &mut stdin, expected_tool, arguments);
        let result = tokio::time::timeout(MCP_TIMEOUT, exchange)
            .await
            .map_err(|_| vision_error("zai_vision_timeout", "Z.AI Vision MCP timed out"))?;
        child.terminate();
        result
    }
}

struct VisionChild {
    child: tokio::process::Child,
    process_group: ProcessGroup,
    _isolated_home: tempfile::TempDir,
}

impl VisionChild {
    fn terminate(&mut self) {
        let _ = self.process_group.kill();
        let _ = self.child.start_kill();
    }
}

impl Drop for VisionChild {
    fn drop(&mut self) {
        self.terminate();
    }
}

async fn run_doctor() -> Result<ZaiVisionDoctorReport, xai_tool_runtime::ToolError> {
    let node_version = command_version("node").await.map_err(|_| {
        vision_error(
            "zai_vision_node_missing",
            "Z.AI Vision MCP requires Node.js 22 or newer",
        )
    })?;
    let major = node_version
        .trim_start_matches('v')
        .split('.')
        .next()
        .and_then(|value| value.parse::<u64>().ok())
        .ok_or_else(|| {
            vision_error(
                "zai_vision_node_version",
                "Z.AI Vision MCP could not determine the Node.js version",
            )
        })?;
    if major < 22 {
        return Err(vision_error(
            "zai_vision_node_version",
            "Z.AI Vision MCP requires Node.js 22 or newer",
        ));
    }
    let npx_version = command_version("npx").await.map_err(|_| {
        vision_error(
            "zai_vision_npx_missing",
            "Z.AI Vision MCP requires npx on PATH",
        )
    })?;
    Ok(ZaiVisionDoctorReport {
        node_version,
        npx_version,
        package_version: ZAI_VISION_MCP_PACKAGE_VERSION,
        package_integrity: ZAI_VISION_MCP_PACKAGE_INTEGRITY,
    })
}

async fn command_version(program: &str) -> Result<String, ()> {
    let mut command = tokio::process::Command::new(program);
    command
        .arg("--version")
        .env_clear()
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .kill_on_drop(true);
    copy_safe_child_environment(&mut command);
    let mut child = command.spawn().map_err(|_| ())?;
    let stdout = child.stdout.take().ok_or(())?;
    let read = async {
        let mut bytes = Vec::new();
        stdout
            .take(257)
            .read_to_end(&mut bytes)
            .await
            .map_err(|_| ())?;
        let status = child.wait().await.map_err(|_| ())?;
        if !status.success() || bytes.is_empty() || bytes.len() > 256 {
            return Err(());
        }
        let value = std::str::from_utf8(&bytes).map_err(|_| ())?.trim();
        if value.is_empty()
            || value.len() > 64
            || !value.chars().all(|character| {
                character.is_ascii_alphanumeric() || matches!(character, '.' | '-' | '+')
            })
        {
            return Err(());
        }
        Ok(value.to_owned())
    };
    tokio::time::timeout(DOCTOR_TIMEOUT, read)
        .await
        .map_err(|_| ())?
}

fn copy_safe_child_environment(command: &mut tokio::process::Command) {
    for name in [
        "PATH",
        "TMPDIR",
        "TMP",
        "TEMP",
        "SYSTEMROOT",
        "SystemRoot",
        "PATHEXT",
    ] {
        if let Some(value) = std::env::var_os(name) {
            command.env(name, value);
        }
    }
}

async fn write_json_line<W: tokio::io::AsyncWrite + Unpin>(
    writer: &mut W,
    value: &serde_json::Value,
) -> Result<(), xai_tool_runtime::ToolError> {
    let bytes = serde_json::to_vec(value).map_err(|_| invalid_vision_response())?;
    if bytes.len() > MAX_STDIO_BYTES {
        return Err(vision_error(
            "zai_vision_request_too_large",
            "Z.AI Vision MCP request exceeds the local transport limit",
        ));
    }
    writer
        .write_all(&bytes)
        .await
        .map_err(|_| invalid_vision_response())?;
    writer
        .write_all(b"\n")
        .await
        .map_err(|_| invalid_vision_response())?;
    writer.flush().await.map_err(|_| invalid_vision_response())
}

async fn read_jsonrpc_response<R: tokio::io::AsyncBufRead + Unpin>(
    reader: &mut R,
    expected_id: i64,
) -> Result<serde_json::Value, xai_tool_runtime::ToolError> {
    loop {
        let mut line = String::new();
        let read = reader
            .read_line(&mut line)
            .await
            .map_err(|_| invalid_vision_response())?;
        if read == 0 || line.len() > MAX_STDIO_BYTES {
            return Err(invalid_vision_response());
        }
        let value: serde_json::Value =
            serde_json::from_str(line.trim()).map_err(|_| invalid_vision_response())?;
        if value.get("id").and_then(serde_json::Value::as_i64) != Some(expected_id) {
            continue;
        }
        if value.get("jsonrpc").and_then(serde_json::Value::as_str) != Some("2.0")
            || value.get("error").is_some()
        {
            return Err(vision_error(
                "zai_vision_rejected",
                "Z.AI Vision MCP rejected the request",
            ));
        }
        return Ok(value);
    }
}

async fn exchange_vision_mcp<R, W>(
    reader: &mut R,
    writer: &mut W,
    expected_tool: &str,
    arguments: serde_json::Value,
) -> Result<serde_json::Value, xai_tool_runtime::ToolError>
where
    R: tokio::io::AsyncBufRead + Unpin,
    W: tokio::io::AsyncWrite + Unpin,
{
    write_json_line(
        writer,
        &serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "initialize",
            "params": {
                "protocolVersion": MCP_PROTOCOL_VERSION,
                "capabilities": {},
                "clientInfo": {
                    "name": "grok-build-enhanced",
                    "version": env!("CARGO_PKG_VERSION")
                }
            }
        }),
    )
    .await?;
    let initialized = read_jsonrpc_response(reader, 1).await?;
    let protocol = initialized
        .pointer("/result/protocolVersion")
        .and_then(serde_json::Value::as_str)
        .ok_or_else(invalid_vision_response)?;
    if !matches!(protocol, "2024-11-05" | "2025-03-26" | "2025-06-18") {
        return Err(vision_error(
            "zai_vision_protocol",
            "Z.AI Vision MCP negotiated an unsupported protocol version",
        ));
    }

    write_json_line(
        writer,
        &serde_json::json!({
            "jsonrpc": "2.0",
            "method": "notifications/initialized",
            "params": {}
        }),
    )
    .await?;
    write_json_line(
        writer,
        &serde_json::json!({
            "jsonrpc": "2.0",
            "id": 2,
            "method": "tools/list",
            "params": {}
        }),
    )
    .await?;
    let listed = read_jsonrpc_response(reader, 2).await?;
    let is_listed = listed
        .pointer("/result/tools")
        .and_then(serde_json::Value::as_array)
        .is_some_and(|tools| {
            tools.iter().any(|tool| {
                tool.get("name").and_then(serde_json::Value::as_str) == Some(expected_tool)
            })
        });
    if !is_listed {
        return Err(vision_error(
            "zai_vision_protocol",
            "The pinned Z.AI Vision MCP package does not expose the requested tool",
        ));
    }

    write_json_line(
        writer,
        &serde_json::json!({
            "jsonrpc": "2.0",
            "id": 3,
            "method": "tools/call",
            "params": {"name": expected_tool, "arguments": arguments}
        }),
    )
    .await?;
    let called = read_jsonrpc_response(reader, 3).await?;
    let result = called
        .get("result")
        .cloned()
        .ok_or_else(invalid_vision_response)?;
    if result.get("isError").and_then(serde_json::Value::as_bool) == Some(true) {
        return Err(vision_error(
            "zai_vision_rejected",
            "Z.AI Vision MCP rejected the media analysis request",
        ));
    }
    Ok(result)
}

fn mcp_text_content(result: &serde_json::Value) -> Result<String, xai_tool_runtime::ToolError> {
    let content = result
        .get("content")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(invalid_vision_response)?;
    let mut text = String::new();
    for block in content {
        if block.get("type").and_then(serde_json::Value::as_str) == Some("text")
            && let Some(value) = block.get("text").and_then(serde_json::Value::as_str)
        {
            if !text.is_empty() {
                text.push('\n');
            }
            text.push_str(value);
        }
    }
    if text.trim().is_empty() {
        return Err(invalid_vision_response());
    }
    Ok(text)
}

fn invalid_vision_response() -> xai_tool_runtime::ToolError {
    vision_error(
        "zai_vision_protocol",
        "Z.AI Vision MCP returned an invalid response",
    )
}

fn vision_error(code: &'static str, message: &'static str) -> xai_tool_runtime::ToolError {
    xai_tool_runtime::ToolError::custom(code, message)
}

#[derive(Clone, Copy)]
enum MediaKind {
    Image,
    Video,
}

fn validate_generated_attachment(
    path: &Path,
    kind: MediaKind,
) -> Result<String, xai_tool_runtime::ToolError> {
    let canonical = std::fs::canonicalize(path).map_err(|_| invalid_media_source(kind))?;
    validate_local_media(&canonical, kind)?;
    Ok(canonical.to_string_lossy().into_owned())
}

fn validate_media_source(
    source: &str,
    kind: MediaKind,
    cwd: &Path,
    session_folder: &Path,
) -> Result<String, xai_tool_runtime::ToolError> {
    let source = source.trim();
    if source.is_empty() || source.len() > 4_096 {
        return Err(invalid_media_source(kind));
    }
    // The local MCP process must never resolve or fetch model-supplied URLs.
    // Users can first download public media through the SSRF-safe WebFetch
    // path, then pass the resulting workspace/session file to Vision.
    if source.contains("://") {
        return Err(invalid_media_source(kind));
    }

    let candidate = PathBuf::from(source);
    let candidate = if candidate.is_absolute() {
        candidate
    } else {
        cwd.join(candidate)
    };
    let canonical = std::fs::canonicalize(candidate).map_err(|_| invalid_media_source(kind))?;
    let cwd = std::fs::canonicalize(cwd).map_err(|_| invalid_media_source(kind))?;
    let session = std::fs::canonicalize(session_folder).map_err(|_| invalid_media_source(kind))?;
    if !canonical.starts_with(&cwd) && !canonical.starts_with(&session) {
        return Err(vision_error(
            "zai_vision_path_denied",
            "Vision MCP local media must be inside the workspace or session folder",
        ));
    }
    validate_local_media(&canonical, kind)?;
    Ok(canonical.to_string_lossy().into_owned())
}

fn validate_local_media(
    canonical: &Path,
    kind: MediaKind,
) -> Result<(), xai_tool_runtime::ToolError> {
    validate_extension(canonical.to_string_lossy().as_ref(), kind)?;
    let metadata = std::fs::metadata(canonical).map_err(|_| invalid_media_source(kind))?;
    let max_bytes = match kind {
        MediaKind::Image => MAX_IMAGE_BYTES,
        MediaKind::Video => MAX_VIDEO_BYTES,
    };
    if !metadata.is_file() || metadata.len() == 0 || metadata.len() > max_bytes {
        return Err(invalid_media_source(kind));
    }
    Ok(())
}

fn validate_extension(source: &str, kind: MediaKind) -> Result<(), xai_tool_runtime::ToolError> {
    let extension = Path::new(source)
        .extension()
        .and_then(|extension| extension.to_str())
        .map(str::to_ascii_lowercase)
        .ok_or_else(|| invalid_media_source(kind))?;
    let valid = match kind {
        MediaKind::Image => matches!(
            extension.as_str(),
            "png" | "jpg" | "jpeg" | "gif" | "webp" | "bmp"
        ),
        MediaKind::Video => matches!(extension.as_str(), "mp4" | "mov" | "m4v"),
    };
    valid
        .then_some(())
        .ok_or_else(|| invalid_media_source(kind))
}

fn invalid_media_source(kind: MediaKind) -> xai_tool_runtime::ToolError {
    match kind {
        MediaKind::Image => vision_error(
            "zai_vision_invalid_image",
            "Vision MCP requires a supported image inside the workspace or session folder",
        ),
        MediaKind::Video => vision_error(
            "zai_vision_invalid_video",
            "Vision MCP requires an MP4, MOV, or M4V up to 8 MiB inside the workspace or session folder",
        ),
    }
}

fn validate_prompt(prompt: &str) -> Result<(), xai_tool_runtime::ToolError> {
    if prompt.trim().is_empty() || prompt.chars().count() > MAX_PROMPT_CHARS {
        return Err(xai_tool_runtime::ToolError::invalid_arguments(format!(
            "prompt must contain between 1 and {MAX_PROMPT_CHARS} characters"
        )));
    }
    Ok(())
}

async fn vision_context(
    ctx: &xai_tool_runtime::ToolCallContext,
) -> Result<(ZaiVisionClient, PathBuf, PathBuf), xai_tool_runtime::ToolError> {
    let resources = shared_resources(ctx)?;
    let resources = resources.lock().await;
    Ok((
        resources.require::<ZaiVisionClient>()?.clone(),
        resources.require::<Cwd>()?.0.clone(),
        resources.require::<SessionFolder>()?.0.clone(),
    ))
}

async fn run_image_tool(
    ctx: xai_tool_runtime::ToolCallContext,
    provider_tool: &'static str,
    mut arguments: serde_json::Value,
    source_fields: &[&str],
) -> Result<ToolOutput, xai_tool_runtime::ToolError> {
    let prompt = arguments
        .get("prompt")
        .and_then(serde_json::Value::as_str)
        .ok_or_else(|| xai_tool_runtime::ToolError::invalid_arguments("prompt is required"))?;
    validate_prompt(prompt)?;
    let (client, cwd, session_folder) = vision_context(&ctx).await?;
    for field in source_fields {
        let source = arguments
            .get(*field)
            .and_then(serde_json::Value::as_str)
            .ok_or_else(|| {
                xai_tool_runtime::ToolError::invalid_arguments(format!("{field} is required"))
            })?;
        let source = validate_media_source(source, MediaKind::Image, &cwd, &session_folder)?;
        arguments
            .as_object_mut()
            .expect("typed Vision arguments serialize as an object")
            .insert((*field).to_owned(), serde_json::Value::String(source));
    }
    let result = client.call_mcp_tool(provider_tool, arguments).await?;
    Ok(ToolOutput::Text(mcp_text_content(&result)?.into()))
}

async fn run_video_tool(
    ctx: xai_tool_runtime::ToolCallContext,
    mut arguments: serde_json::Value,
) -> Result<ToolOutput, xai_tool_runtime::ToolError> {
    let prompt = arguments
        .get("prompt")
        .and_then(serde_json::Value::as_str)
        .ok_or_else(|| xai_tool_runtime::ToolError::invalid_arguments("prompt is required"))?;
    validate_prompt(prompt)?;
    let (client, cwd, session_folder) = vision_context(&ctx).await?;
    let source = arguments
        .get("video_source")
        .and_then(serde_json::Value::as_str)
        .ok_or_else(|| {
            xai_tool_runtime::ToolError::invalid_arguments("video_source is required")
        })?;
    let source = validate_media_source(source, MediaKind::Video, &cwd, &session_folder)?;
    arguments
        .as_object_mut()
        .expect("typed Vision arguments serialize as an object")
        .insert("video_source".to_owned(), serde_json::Value::String(source));
    let result = client.call_mcp_tool("analyze_video", arguments).await?;
    Ok(ToolOutput::Text(mcp_text_content(&result)?.into()))
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct VisionImagePromptInput {
    pub image_source: String,
    pub prompt: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct VisionExtractTextInput {
    pub image_source: String,
    pub prompt: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub programming_language: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct VisionDiagnoseErrorInput {
    pub image_source: String,
    pub prompt: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct VisionDiagramInput {
    pub image_source: String,
    pub prompt: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub diagram_type: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct VisionDataInput {
    pub image_source: String,
    pub prompt: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub analysis_focus: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum VisionArtifactType {
    Code,
    Prompt,
    Spec,
    Description,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct VisionUiArtifactInput {
    pub image_source: String,
    pub output_type: VisionArtifactType,
    pub prompt: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct VisionUiDiffInput {
    pub expected_image_source: String,
    pub actual_image_source: String,
    pub prompt: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct VisionVideoInput {
    pub video_source: String,
    pub prompt: String,
}

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct VisionDoctorInput {}

macro_rules! dynamic_input {
    ($($input:ty),+ $(,)?) => {$ (
        impl From<$input> for ToolInput {
            fn from(input: $input) -> Self {
                Self::Dynamic(serde_json::to_value(input).expect("Vision input serializes"))
            }
        }
    )+ };
}

dynamic_input!(
    VisionImagePromptInput,
    VisionExtractTextInput,
    VisionDiagnoseErrorInput,
    VisionDiagramInput,
    VisionDataInput,
    VisionUiArtifactInput,
    VisionUiDiffInput,
    VisionVideoInput,
    VisionDoctorInput,
);

macro_rules! vision_tool_metadata {
    ($tool:ty, $description:expr) => {
        impl ToolMetadata for $tool {
            fn kind(&self) -> ToolKind {
                ToolKind::Read
            }
            fn tool_namespace(&self) -> ToolNamespace {
                ToolNamespace::GrokBuild
            }
            fn description_template(&self) -> &str {
                $description
            }
            fn requires_expr(&self) -> Expr<ToolRequirement> {
                Expr::True
            }
        }
    };
}

macro_rules! vision_tool_common {
    ($name:expr, $description:expr) => {
        fn id(&self) -> xai_tool_protocol::ToolId {
            xai_tool_protocol::ToolId::new($name).expect("valid tool id")
        }
        fn description(
            &self,
            _ctx: &xai_tool_runtime::ListToolsContext,
        ) -> xai_tool_types::ToolDescription {
            xai_tool_types::ToolDescription::new($name, $description)
        }
        fn capabilities(&self) -> xai_tool_protocol::ToolCapabilities {
            xai_tool_protocol::ToolCapabilities {
                is_read_only: true,
                tool_scope: Some(xai_tool_protocol::ToolScope::Read),
                ..Default::default()
            }
        }
    };
}

#[derive(Debug, Default)]
pub struct ZaiVisionDoctorTool;
#[derive(Debug, Default)]
pub struct ZaiVisionUiToArtifactTool;
#[derive(Debug, Default)]
pub struct ZaiVisionExtractTextTool;
#[derive(Debug, Default)]
pub struct ZaiVisionDiagnoseErrorTool;
#[derive(Debug, Default)]
pub struct ZaiVisionUnderstandDiagramTool;
#[derive(Debug, Default)]
pub struct ZaiVisionAnalyzeDataTool;
#[derive(Debug, Default)]
pub struct ZaiVisionUiDiffTool;
#[derive(Debug, Default)]
pub struct ZaiVisionAnalyzeImageTool;
#[derive(Debug, Default)]
pub struct ZaiVisionAnalyzeVideoTool;

const DOCTOR_DESCRIPTION: &str = "Check the opt-in Z.AI Vision MCP runtime without exposing credentials: Node.js >=22, npx, and the exact pinned package version/integrity.";
const UI_ARTIFACT_DESCRIPTION: &str = "Convert a UI screenshot into frontend code, a recreation prompt, a design specification, or a description using opt-in Z.AI Coding Plan Vision MCP.";
const EXTRACT_TEXT_DESCRIPTION: &str = "Extract code, terminal output, documentation, or other text from a screenshot using opt-in Z.AI Coding Plan Vision MCP.";
const DIAGNOSE_ERROR_DESCRIPTION: &str = "Diagnose an error screenshot and propose actionable fixes using opt-in Z.AI Coding Plan Vision MCP.";
const DIAGRAM_DESCRIPTION: &str = "Interpret an architecture, flow, UML, ER, sequence, or other technical diagram using opt-in Z.AI Coding Plan Vision MCP.";
const DATA_DESCRIPTION: &str = "Analyze a chart, graph, dashboard, or other data visualization using opt-in Z.AI Coding Plan Vision MCP.";
const UI_DIFF_DESCRIPTION: &str = "Compare expected and actual UI screenshots and report visual or implementation drift using opt-in Z.AI Coding Plan Vision MCP.";
const IMAGE_DESCRIPTION: &str = "Analyze an image using opt-in Z.AI Coding Plan Vision MCP when no specialized Vision tool fits.";
const VIDEO_DESCRIPTION: &str = "Analyze a local MP4, MOV, or M4V video up to 8 MiB inside the workspace/session using opt-in Z.AI Coding Plan Vision MCP.";

vision_tool_metadata!(ZaiVisionDoctorTool, DOCTOR_DESCRIPTION);
vision_tool_metadata!(ZaiVisionUiToArtifactTool, UI_ARTIFACT_DESCRIPTION);
vision_tool_metadata!(ZaiVisionExtractTextTool, EXTRACT_TEXT_DESCRIPTION);
vision_tool_metadata!(ZaiVisionDiagnoseErrorTool, DIAGNOSE_ERROR_DESCRIPTION);
vision_tool_metadata!(ZaiVisionUnderstandDiagramTool, DIAGRAM_DESCRIPTION);
vision_tool_metadata!(ZaiVisionAnalyzeDataTool, DATA_DESCRIPTION);
vision_tool_metadata!(ZaiVisionUiDiffTool, UI_DIFF_DESCRIPTION);
vision_tool_metadata!(ZaiVisionAnalyzeImageTool, IMAGE_DESCRIPTION);
vision_tool_metadata!(ZaiVisionAnalyzeVideoTool, VIDEO_DESCRIPTION);

impl xai_tool_runtime::Tool for ZaiVisionDoctorTool {
    type Args = VisionDoctorInput;
    type Output = ToolOutput;
    vision_tool_common!(ZAI_VISION_DOCTOR_TOOL_NAME, DOCTOR_DESCRIPTION);
    async fn run(
        &self,
        ctx: xai_tool_runtime::ToolCallContext,
        _input: VisionDoctorInput,
    ) -> Result<ToolOutput, xai_tool_runtime::ToolError> {
        let (client, _, _) = vision_context(&ctx).await?;
        Ok(ToolOutput::Text(client.doctor().await?.render().into()))
    }
}

macro_rules! impl_image_vision_tool {
    ($tool:ty, $args:ty, $name:expr, $description:expr, $provider_tool:expr) => {
        impl xai_tool_runtime::Tool for $tool {
            type Args = $args;
            type Output = ToolOutput;
            vision_tool_common!($name, $description);
            async fn run(
                &self,
                ctx: xai_tool_runtime::ToolCallContext,
                input: $args,
            ) -> Result<ToolOutput, xai_tool_runtime::ToolError> {
                run_image_tool(
                    ctx,
                    $provider_tool,
                    serde_json::to_value(input).expect("Vision input serializes"),
                    &["image_source"],
                )
                .await
            }
        }
    };
}

impl_image_vision_tool!(
    ZaiVisionUiToArtifactTool,
    VisionUiArtifactInput,
    ZAI_VISION_UI_TO_ARTIFACT_TOOL_NAME,
    UI_ARTIFACT_DESCRIPTION,
    "ui_to_artifact"
);
impl_image_vision_tool!(
    ZaiVisionExtractTextTool,
    VisionExtractTextInput,
    ZAI_VISION_EXTRACT_TEXT_TOOL_NAME,
    EXTRACT_TEXT_DESCRIPTION,
    "extract_text_from_screenshot"
);
impl_image_vision_tool!(
    ZaiVisionDiagnoseErrorTool,
    VisionDiagnoseErrorInput,
    ZAI_VISION_DIAGNOSE_ERROR_TOOL_NAME,
    DIAGNOSE_ERROR_DESCRIPTION,
    "diagnose_error_screenshot"
);
impl_image_vision_tool!(
    ZaiVisionUnderstandDiagramTool,
    VisionDiagramInput,
    ZAI_VISION_UNDERSTAND_DIAGRAM_TOOL_NAME,
    DIAGRAM_DESCRIPTION,
    "understand_technical_diagram"
);
impl_image_vision_tool!(
    ZaiVisionAnalyzeDataTool,
    VisionDataInput,
    ZAI_VISION_ANALYZE_DATA_TOOL_NAME,
    DATA_DESCRIPTION,
    "analyze_data_visualization"
);
impl_image_vision_tool!(
    ZaiVisionAnalyzeImageTool,
    VisionImagePromptInput,
    ZAI_VISION_ANALYZE_IMAGE_TOOL_NAME,
    IMAGE_DESCRIPTION,
    "analyze_image"
);

impl xai_tool_runtime::Tool for ZaiVisionUiDiffTool {
    type Args = VisionUiDiffInput;
    type Output = ToolOutput;
    vision_tool_common!(ZAI_VISION_UI_DIFF_TOOL_NAME, UI_DIFF_DESCRIPTION);
    async fn run(
        &self,
        ctx: xai_tool_runtime::ToolCallContext,
        input: VisionUiDiffInput,
    ) -> Result<ToolOutput, xai_tool_runtime::ToolError> {
        run_image_tool(
            ctx,
            "ui_diff_check",
            serde_json::to_value(input).expect("Vision input serializes"),
            &["expected_image_source", "actual_image_source"],
        )
        .await
    }
}

impl xai_tool_runtime::Tool for ZaiVisionAnalyzeVideoTool {
    type Args = VisionVideoInput;
    type Output = ToolOutput;
    vision_tool_common!(ZAI_VISION_ANALYZE_VIDEO_TOOL_NAME, VIDEO_DESCRIPTION);
    async fn run(
        &self,
        ctx: xai_tool_runtime::ToolCallContext,
        input: VisionVideoInput,
    ) -> Result<ToolOutput, xai_tool_runtime::ToolError> {
        run_video_tool(
            ctx,
            serde_json::to_value(input).expect("Vision input serializes"),
        )
        .await
    }
}

pub fn vision_tool_configs() -> [crate::registry::types::ToolConfig; 9] {
    [
        crate::registry::types::ToolConfig::for_tool::<ZaiVisionDoctorTool>(),
        crate::registry::types::ToolConfig::for_tool::<ZaiVisionUiToArtifactTool>(),
        crate::registry::types::ToolConfig::for_tool::<ZaiVisionExtractTextTool>(),
        crate::registry::types::ToolConfig::for_tool::<ZaiVisionDiagnoseErrorTool>(),
        crate::registry::types::ToolConfig::for_tool::<ZaiVisionUnderstandDiagramTool>(),
        crate::registry::types::ToolConfig::for_tool::<ZaiVisionAnalyzeDataTool>(),
        crate::registry::types::ToolConfig::for_tool::<ZaiVisionUiDiffTool>(),
        crate::registry::types::ToolConfig::for_tool::<ZaiVisionAnalyzeImageTool>(),
        crate::registry::types::ToolConfig::for_tool::<ZaiVisionAnalyzeVideoTool>(),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vision_enablement_parser_is_explicit_and_case_insensitive() {
        for enabled in ["1", "true", "TRUE", " yes ", "On"] {
            assert!(
                parse_vision_mcp_enabled(Some(enabled)),
                "rejected {enabled:?}"
            );
        }
        for disabled in [None, Some(""), Some("0"), Some("false"), Some("disabled")] {
            assert!(!parse_vision_mcp_enabled(disabled));
        }
    }

    #[test]
    fn local_media_stays_inside_allowed_roots_and_video_is_bounded() {
        let cwd = tempfile::tempdir().unwrap();
        let session = tempfile::tempdir().unwrap();
        let image = cwd.path().join("screen.png");
        std::fs::write(&image, b"png").unwrap();
        assert!(
            validate_media_source(
                image.to_str().unwrap(),
                MediaKind::Image,
                cwd.path(),
                session.path()
            )
            .is_ok()
        );

        let outside = tempfile::NamedTempFile::with_suffix(".png").unwrap();
        assert!(
            validate_media_source(
                outside.path().to_str().unwrap(),
                MediaKind::Image,
                cwd.path(),
                session.path()
            )
            .is_err()
        );

        let video = session.path().join("clip.mp4");
        let file = std::fs::File::create(&video).unwrap();
        file.set_len(MAX_VIDEO_BYTES + 1).unwrap();
        assert!(
            validate_media_source(
                video.to_str().unwrap(),
                MediaKind::Video,
                cwd.path(),
                session.path()
            )
            .is_err()
        );
    }

    #[test]
    fn remote_media_is_rejected_before_the_local_mcp_process() {
        let cwd = tempfile::tempdir().unwrap();
        let session = tempfile::tempdir().unwrap();
        for source in [
            "http://example.com/screen.png",
            "https://example.com/screen.png",
            "https://localhost/screen.png",
            "https://127.0.0.1/screen.png",
            "file:///tmp/screen.png",
        ] {
            assert!(
                validate_media_source(source, MediaKind::Image, cwd.path(), session.path())
                    .is_err(),
                "accepted {source}"
            );
        }
    }

    #[tokio::test]
    async fn stdio_exchange_performs_initialize_list_and_call_sequence() {
        let (client, server) = tokio::io::duplex(16 * 1024);
        let (client_read, mut client_write) = tokio::io::split(client);
        let mut client_reader = BufReader::new(client_read);

        let server = tokio::spawn(async move {
            let (server_read, mut server_write) = tokio::io::split(server);
            let mut server_reader = BufReader::new(server_read);
            let mut line = String::new();

            server_reader.read_line(&mut line).await.unwrap();
            let initialize: serde_json::Value = serde_json::from_str(line.trim()).unwrap();
            assert_eq!(initialize["method"], "initialize");
            assert_eq!(
                initialize["params"]["protocolVersion"],
                MCP_PROTOCOL_VERSION
            );
            write_json_line(
                &mut server_write,
                &serde_json::json!({
                    "jsonrpc": "2.0",
                    "id": 1,
                    "result": {"protocolVersion": MCP_PROTOCOL_VERSION}
                }),
            )
            .await
            .unwrap();

            line.clear();
            server_reader.read_line(&mut line).await.unwrap();
            let initialized: serde_json::Value = serde_json::from_str(line.trim()).unwrap();
            assert_eq!(initialized["method"], "notifications/initialized");

            line.clear();
            server_reader.read_line(&mut line).await.unwrap();
            let list: serde_json::Value = serde_json::from_str(line.trim()).unwrap();
            assert_eq!(list["method"], "tools/list");
            write_json_line(
                &mut server_write,
                &serde_json::json!({
                    "jsonrpc": "2.0",
                    "id": 2,
                    "result": {"tools": [{"name": "analyze_image"}]}
                }),
            )
            .await
            .unwrap();

            line.clear();
            server_reader.read_line(&mut line).await.unwrap();
            let call: serde_json::Value = serde_json::from_str(line.trim()).unwrap();
            assert_eq!(call["method"], "tools/call");
            assert_eq!(call["params"]["name"], "analyze_image");
            assert_eq!(call["params"]["arguments"]["prompt"], "describe");
            write_json_line(
                &mut server_write,
                &serde_json::json!({
                    "jsonrpc": "2.0",
                    "id": 3,
                    "result": {
                        "content": [{"type": "text", "text": "description"}]
                    }
                }),
            )
            .await
            .unwrap();
        });

        let result = exchange_vision_mcp(
            &mut client_reader,
            &mut client_write,
            "analyze_image",
            serde_json::json!({"image_source": "/workspace/screen.png", "prompt": "describe"}),
        )
        .await
        .unwrap();
        assert_eq!(mcp_text_content(&result).unwrap(), "description");
        server.await.unwrap();
    }

    #[test]
    fn package_is_exactly_pinned() {
        assert_eq!(ZAI_VISION_MCP_PACKAGE, "@z_ai/mcp-server@0.1.4");
        assert!(!ZAI_VISION_MCP_PACKAGE.contains("latest"));
        assert!(ZAI_VISION_MCP_PACKAGE_INTEGRITY.starts_with("sha512-"));
    }
}
